--
-- PostgreSQL database dump
--

-- Dumped from database version 13.18 (Debian 13.18-1.pgdg120+1)
-- Dumped by pg_dump version 13.18 (Debian 13.18-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_app_blacklistedip; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_blacklistedip (
    id bigint NOT NULL,
    ip_address inet NOT NULL,
    added_at timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_app_blacklistedip OWNER TO postgres;

--
-- Name: auth_app_blacklistedip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_app_blacklistedip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_app_blacklistedip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    id character varying(70) NOT NULL,
    first_name character varying(256) NOT NULL,
    last_name character varying(256) NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(20),
    profile_picture character varying(100),
    timezone character varying(100),
    plan_type character varying(20) NOT NULL,
    trial_expiry_date timestamp with time zone,
    is_staff boolean NOT NULL,
    is_admin boolean NOT NULL,
    is_superuser boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id character varying(256)
);


ALTER TABLE public.auth_app_user OWNER TO postgres;

--
-- Name: auth_app_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_user_groups (
    id bigint NOT NULL,
    user_id character varying(70) NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_app_user_groups OWNER TO postgres;

--
-- Name: auth_app_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_app_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_app_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_app_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_user_user_permissions (
    id bigint NOT NULL,
    user_id character varying(70) NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_app_user_user_permissions OWNER TO postgres;

--
-- Name: auth_app_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_app_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_app_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_app_visitor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_visitor (
    id bigint NOT NULL,
    ip_address inet NOT NULL,
    device character varying(100) NOT NULL,
    os character varying(100) NOT NULL,
    browser character varying(100) NOT NULL,
    visited_at timestamp with time zone NOT NULL,
    page character varying(200) NOT NULL,
    method character varying(10)
);


ALTER TABLE public.auth_app_visitor OWNER TO postgres;

--
-- Name: auth_app_visitor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_app_visitor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_app_visitor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_app_blog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_blog (
    id character varying(70) NOT NULL,
    title character varying(200) NOT NULL,
    slug character varying(220) NOT NULL,
    content text NOT NULL,
    image character varying(100),
    video character varying(100),
    status character varying(10) NOT NULL,
    scheduled_date timestamp with time zone,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    views integer NOT NULL,
    meta_title character varying(60) NOT NULL,
    meta_description text NOT NULL,
    author_id character varying(70) NOT NULL,
    category_id bigint,
    CONSTRAINT blog_app_blog_views_check CHECK ((views >= 0))
);


ALTER TABLE public.blog_app_blog OWNER TO postgres;

--
-- Name: blog_app_blog_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_blog_tags (
    id bigint NOT NULL,
    blog_id character varying(70) NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.blog_app_blog_tags OWNER TO postgres;

--
-- Name: blog_app_blog_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog_app_blog_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_app_blog_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_app_blogviewer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_blogviewer (
    id character varying(70) NOT NULL,
    ip_address inet NOT NULL,
    view_duration interval,
    created_at timestamp with time zone NOT NULL,
    blog_id character varying(70) NOT NULL,
    viewer_id character varying(70)
);


ALTER TABLE public.blog_app_blogviewer OWNER TO postgres;

--
-- Name: blog_app_bookmark; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_bookmark (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blog_id character varying(70) NOT NULL,
    user_id character varying(70) NOT NULL
);


ALTER TABLE public.blog_app_bookmark OWNER TO postgres;

--
-- Name: blog_app_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog_app_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_app_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_app_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL
);


ALTER TABLE public.blog_app_category OWNER TO postgres;

--
-- Name: blog_app_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog_app_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_app_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_app_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_comment (
    id character varying(70) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blog_id character varying(70) NOT NULL,
    parent_id character varying(70),
    user_id character varying(70) NOT NULL,
    can_publish_comment boolean NOT NULL
);


ALTER TABLE public.blog_app_comment OWNER TO postgres;

--
-- Name: blog_app_like; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_like (
    id character varying(70) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blog_id character varying(70) NOT NULL,
    user_id character varying(70) NOT NULL
);


ALTER TABLE public.blog_app_like OWNER TO postgres;

--
-- Name: blog_app_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_app_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.blog_app_tag OWNER TO postgres;

--
-- Name: blog_app_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog_app_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_app_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calendar_app_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.calendar_app_event (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    employee_id character varying(70),
    created_by_id character varying(70),
    customer_id uuid,
    event_type character varying(50) NOT NULL
);


ALTER TABLE public.calendar_app_event OWNER TO postgres;

--
-- Name: career_app_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_answer (
    id character varying(256) NOT NULL,
    text_answer text,
    created_at timestamp with time zone NOT NULL,
    question_id character varying(256) NOT NULL,
    email character varying(256) NOT NULL,
    full_name character varying(256) NOT NULL
);


ALTER TABLE public.career_app_answer OWNER TO postgres;

--
-- Name: career_app_answer_selected_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_answer_selected_options (
    id bigint NOT NULL,
    answer_id character varying(256) NOT NULL,
    option_id character varying(256) NOT NULL
);


ALTER TABLE public.career_app_answer_selected_options OWNER TO postgres;

--
-- Name: career_app_answer_selected_options_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_app_answer_selected_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_app_answer_selected_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_app_career; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_career (
    id character varying(256) NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.career_app_career OWNER TO postgres;

--
-- Name: career_app_careerapplication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_careerapplication (
    id character varying(70) NOT NULL,
    user_id character varying(100),
    resume character varying(100),
    full_name character varying(256) NOT NULL,
    email character varying(256) NOT NULL,
    primary_profession character varying(256),
    project_link character varying(256),
    github_repo character varying(256),
    career_id character varying(256),
    city character varying(256),
    country character varying(256),
    state character varying(256)
);


ALTER TABLE public.career_app_careerapplication OWNER TO postgres;

--
-- Name: career_app_option; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_option (
    id character varying(256) NOT NULL,
    text character varying(255) NOT NULL,
    question_id character varying(256) NOT NULL,
    is_correct boolean NOT NULL
);


ALTER TABLE public.career_app_option OWNER TO postgres;

--
-- Name: career_app_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_question (
    id character varying(256) NOT NULL,
    text character varying(500) NOT NULL,
    question_type character varying(50) NOT NULL,
    career_id character varying(256) NOT NULL
);


ALTER TABLE public.career_app_question OWNER TO postgres;

--
-- Name: career_app_requirement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_app_requirement (
    id character varying(256) NOT NULL,
    description character varying(255) NOT NULL,
    career_id character varying(256) NOT NULL
);


ALTER TABLE public.career_app_requirement OWNER TO postgres;

--
-- Name: cms_casestudy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_casestudy (
    id bigint NOT NULL,
    title character varying(256) NOT NULL,
    descriptiion text NOT NULL,
    image character varying(100) NOT NULL
);


ALTER TABLE public.cms_casestudy OWNER TO postgres;

--
-- Name: cms_casestudy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_casestudy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_casestudy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_contactus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_contactus (
    id bigint NOT NULL,
    full_name character varying(256) NOT NULL,
    email character varying(256) NOT NULL,
    company_size character varying(20),
    message text NOT NULL
);


ALTER TABLE public.cms_contactus OWNER TO postgres;

--
-- Name: cms_contactus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_contactus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_contactus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_faqs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_faqs (
    id bigint NOT NULL,
    question character varying(256) NOT NULL,
    answer text NOT NULL
);


ALTER TABLE public.cms_faqs OWNER TO postgres;

--
-- Name: cms_faqs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_faqs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_faqs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_headertitle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_headertitle (
    id bigint NOT NULL,
    title character varying(256) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    description text NOT NULL,
    page character varying(256) NOT NULL,
    image character varying(100),
    video character varying(100)
);


ALTER TABLE public.cms_headertitle OWNER TO postgres;

--
-- Name: cms_headertitle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_headertitle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_headertitle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_logo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_logo (
    id bigint NOT NULL,
    logo character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.cms_logo OWNER TO postgres;

--
-- Name: cms_logo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_logo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_logo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_taxpayer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_taxpayer (
    id character varying(256) NOT NULL,
    address_reference character varying(256),
    visiting_hours character varying(256),
    representation_rnc character varying(256),
    name_of_representative character varying(256),
    representative_phone character varying(256),
    representative_cell_phone character varying(256),
    representative_email character varying(256),
    operation_carried_out_in_premise character varying(256),
    street_of_warehouse character varying(256),
    store_or_warehouse_number character varying(256),
    province_of_warehouse character varying(256),
    warehouse_reference character varying(256),
    local_administration character varying(256),
    warehouse_sector character varying(256),
    tax_payer_rnc character varying(256),
    name_of_tax_payer character varying(256),
    trade_name character varying(256),
    tax_payer_telephone character varying(256),
    tax_payer_cell_phone character varying(256),
    tax_payer_email character varying(256),
    tax_payer_number character varying(256),
    tax_payer_sector character varying(256),
    tax_payer_province character varying(256)
);


ALTER TABLE public.cms_taxpayer OWNER TO postgres;

--
-- Name: cms_taxpayermedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_taxpayermedia (
    id bigint NOT NULL,
    media_file character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    taxpayer_id character varying(256) NOT NULL
);


ALTER TABLE public.cms_taxpayermedia OWNER TO postgres;

--
-- Name: cms_taxpayermedia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_taxpayermedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_taxpayermedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cms_testimonial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cms_testimonial (
    id bigint NOT NULL,
    full_name character varying(256) NOT NULL,
    rating numeric(5,2),
    message text NOT NULL,
    role character varying(256),
    image character varying(100),
    created_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    meta_data jsonb
);


ALTER TABLE public.cms_testimonial OWNER TO postgres;

--
-- Name: cms_testimonial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cms_testimonial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cms_testimonial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers_customer (
    id uuid NOT NULL,
    customer_id character varying(256) NOT NULL,
    first_name character varying(256) NOT NULL,
    last_name character varying(256) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(15),
    address text
);


ALTER TABLE public.customers_customer OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id character varying(70) NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: employee_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_employee (
    id character varying(70) NOT NULL,
    first_name character varying(256) NOT NULL,
    last_name character varying(256) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(15),
    is_active boolean NOT NULL,
    date_of_birth date,
    date_joined timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    country character varying,
    profile_picture character varying(100),
    qr_code character varying(100),
    role character varying(256),
    team character varying(256),
    employee_id character varying(256) NOT NULL
);


ALTER TABLE public.employee_employee OWNER TO postgres;

--
-- Name: employee_socialmedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_socialmedia (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    link character varying(200) NOT NULL,
    employee_id character varying(70) NOT NULL
);


ALTER TABLE public.employee_socialmedia OWNER TO postgres;

--
-- Name: employee_socialmedia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_socialmedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_socialmedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_app_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_app_transaction (
    id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_id character varying(256) NOT NULL,
    customer_id character varying(256) NOT NULL,
    customer_email character varying(254) NOT NULL,
    client_secret character varying(256),
    currency character varying(10) NOT NULL,
    status character varying(50) NOT NULL,
    payment_method character varying(50),
    payment_status character varying(50) NOT NULL,
    meta_data jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.payment_app_transaction OWNER TO postgres;

--
-- Name: auth_app_blacklistedip auth_app_blacklistedip_ip_address_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_blacklistedip
    ADD CONSTRAINT auth_app_blacklistedip_ip_address_key UNIQUE (ip_address);


--
-- Name: auth_app_blacklistedip auth_app_blacklistedip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_blacklistedip
    ADD CONSTRAINT auth_app_blacklistedip_pkey PRIMARY KEY (id);


--
-- Name: auth_app_user auth_app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user
    ADD CONSTRAINT auth_app_user_email_key UNIQUE (email);


--
-- Name: auth_app_user_groups auth_app_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_groups
    ADD CONSTRAINT auth_app_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_app_user_groups auth_app_user_groups_user_id_group_id_5f174ff0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_groups
    ADD CONSTRAINT auth_app_user_groups_user_id_group_id_5f174ff0_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_app_user auth_app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user
    ADD CONSTRAINT auth_app_user_pkey PRIMARY KEY (id);


--
-- Name: auth_app_user_user_permissions auth_app_user_user_permi_user_id_permission_id_727a8e97_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_user_permissions
    ADD CONSTRAINT auth_app_user_user_permi_user_id_permission_id_727a8e97_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_app_user_user_permissions auth_app_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_user_permissions
    ADD CONSTRAINT auth_app_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_app_visitor auth_app_visitor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_visitor
    ADD CONSTRAINT auth_app_visitor_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: blog_app_blog blog_app_blog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog
    ADD CONSTRAINT blog_app_blog_pkey PRIMARY KEY (id);


--
-- Name: blog_app_blog blog_app_blog_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog
    ADD CONSTRAINT blog_app_blog_slug_key UNIQUE (slug);


--
-- Name: blog_app_blog_tags blog_app_blog_tags_blog_id_tag_id_a848f23e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog_tags
    ADD CONSTRAINT blog_app_blog_tags_blog_id_tag_id_a848f23e_uniq UNIQUE (blog_id, tag_id);


--
-- Name: blog_app_blog_tags blog_app_blog_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog_tags
    ADD CONSTRAINT blog_app_blog_tags_pkey PRIMARY KEY (id);


--
-- Name: blog_app_blogviewer blog_app_blogviewer_blog_id_ip_address_3f27184d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blogviewer
    ADD CONSTRAINT blog_app_blogviewer_blog_id_ip_address_3f27184d_uniq UNIQUE (blog_id, ip_address);


--
-- Name: blog_app_blogviewer blog_app_blogviewer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blogviewer
    ADD CONSTRAINT blog_app_blogviewer_pkey PRIMARY KEY (id);


--
-- Name: blog_app_bookmark blog_app_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_bookmark
    ADD CONSTRAINT blog_app_bookmark_pkey PRIMARY KEY (id);


--
-- Name: blog_app_category blog_app_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_category
    ADD CONSTRAINT blog_app_category_name_key UNIQUE (name);


--
-- Name: blog_app_category blog_app_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_category
    ADD CONSTRAINT blog_app_category_pkey PRIMARY KEY (id);


--
-- Name: blog_app_category blog_app_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_category
    ADD CONSTRAINT blog_app_category_slug_key UNIQUE (slug);


--
-- Name: blog_app_comment blog_app_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_comment
    ADD CONSTRAINT blog_app_comment_pkey PRIMARY KEY (id);


--
-- Name: blog_app_like blog_app_like_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_like
    ADD CONSTRAINT blog_app_like_pkey PRIMARY KEY (id);


--
-- Name: blog_app_tag blog_app_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_tag
    ADD CONSTRAINT blog_app_tag_name_key UNIQUE (name);


--
-- Name: blog_app_tag blog_app_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_tag
    ADD CONSTRAINT blog_app_tag_pkey PRIMARY KEY (id);


--
-- Name: calendar_app_event calendar_app_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_app_event
    ADD CONSTRAINT calendar_app_event_pkey PRIMARY KEY (id);


--
-- Name: career_app_answer career_app_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer
    ADD CONSTRAINT career_app_answer_pkey PRIMARY KEY (id);


--
-- Name: career_app_answer_selected_options career_app_answer_select_answer_id_option_id_20e591a7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer_selected_options
    ADD CONSTRAINT career_app_answer_select_answer_id_option_id_20e591a7_uniq UNIQUE (answer_id, option_id);


--
-- Name: career_app_answer_selected_options career_app_answer_selected_options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer_selected_options
    ADD CONSTRAINT career_app_answer_selected_options_pkey PRIMARY KEY (id);


--
-- Name: career_app_career career_app_career_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_career
    ADD CONSTRAINT career_app_career_pkey PRIMARY KEY (id);


--
-- Name: career_app_careerapplication career_app_careerapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_careerapplication
    ADD CONSTRAINT career_app_careerapplication_pkey PRIMARY KEY (id);


--
-- Name: career_app_option career_app_option_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_option
    ADD CONSTRAINT career_app_option_pkey PRIMARY KEY (id);


--
-- Name: career_app_question career_app_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_question
    ADD CONSTRAINT career_app_question_pkey PRIMARY KEY (id);


--
-- Name: career_app_requirement career_app_requirement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_requirement
    ADD CONSTRAINT career_app_requirement_pkey PRIMARY KEY (id);


--
-- Name: cms_casestudy cms_casestudy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_casestudy
    ADD CONSTRAINT cms_casestudy_pkey PRIMARY KEY (id);


--
-- Name: cms_contactus cms_contactus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_contactus
    ADD CONSTRAINT cms_contactus_pkey PRIMARY KEY (id);


--
-- Name: cms_faqs cms_faqs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_faqs
    ADD CONSTRAINT cms_faqs_pkey PRIMARY KEY (id);


--
-- Name: cms_headertitle cms_headertitle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_headertitle
    ADD CONSTRAINT cms_headertitle_pkey PRIMARY KEY (id);


--
-- Name: cms_logo cms_logo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_logo
    ADD CONSTRAINT cms_logo_pkey PRIMARY KEY (id);


--
-- Name: cms_taxpayer cms_taxpayer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_taxpayer
    ADD CONSTRAINT cms_taxpayer_pkey PRIMARY KEY (id);


--
-- Name: cms_taxpayermedia cms_taxpayermedia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_taxpayermedia
    ADD CONSTRAINT cms_taxpayermedia_pkey PRIMARY KEY (id);


--
-- Name: cms_testimonial cms_testimonial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_testimonial
    ADD CONSTRAINT cms_testimonial_pkey PRIMARY KEY (id);


--
-- Name: customers_customer customers_customer_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customer
    ADD CONSTRAINT customers_customer_customer_id_key UNIQUE (customer_id);


--
-- Name: customers_customer customers_customer_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customer
    ADD CONSTRAINT customers_customer_email_key UNIQUE (email);


--
-- Name: customers_customer customers_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customer
    ADD CONSTRAINT customers_customer_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: employee_employee employee_employee_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_employee
    ADD CONSTRAINT employee_employee_email_key UNIQUE (email);


--
-- Name: employee_employee employee_employee_employee_id_f303a754_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_employee
    ADD CONSTRAINT employee_employee_employee_id_f303a754_uniq UNIQUE (employee_id);


--
-- Name: employee_employee employee_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_employee
    ADD CONSTRAINT employee_employee_pkey PRIMARY KEY (id);


--
-- Name: employee_socialmedia employee_socialmedia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_socialmedia
    ADD CONSTRAINT employee_socialmedia_pkey PRIMARY KEY (id);


--
-- Name: payment_app_transaction payment_app_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_app_transaction
    ADD CONSTRAINT payment_app_transaction_pkey PRIMARY KEY (id);


--
-- Name: payment_app_transaction payment_app_transaction_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_app_transaction
    ADD CONSTRAINT payment_app_transaction_transaction_id_key UNIQUE (transaction_id);


--
-- Name: auth_app_user_email_fcbe118b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_email_fcbe118b_like ON public.auth_app_user USING btree (email varchar_pattern_ops);


--
-- Name: auth_app_user_groups_group_id_b4576925; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_groups_group_id_b4576925 ON public.auth_app_user_groups USING btree (group_id);


--
-- Name: auth_app_user_groups_user_id_2b6e45f5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_groups_user_id_2b6e45f5 ON public.auth_app_user_groups USING btree (user_id);


--
-- Name: auth_app_user_groups_user_id_2b6e45f5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_groups_user_id_2b6e45f5_like ON public.auth_app_user_groups USING btree (user_id varchar_pattern_ops);


--
-- Name: auth_app_user_id_c8050a1d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_id_c8050a1d_like ON public.auth_app_user USING btree (id varchar_pattern_ops);


--
-- Name: auth_app_user_user_permissions_permission_id_cc1b2396; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_user_permissions_permission_id_cc1b2396 ON public.auth_app_user_user_permissions USING btree (permission_id);


--
-- Name: auth_app_user_user_permissions_user_id_b7c37328; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_user_permissions_user_id_b7c37328 ON public.auth_app_user_user_permissions USING btree (user_id);


--
-- Name: auth_app_user_user_permissions_user_id_b7c37328_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_app_user_user_permissions_user_id_b7c37328_like ON public.auth_app_user_user_permissions USING btree (user_id varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: blog_app_blog_author_id_92ddd532; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_author_id_92ddd532 ON public.blog_app_blog USING btree (author_id);


--
-- Name: blog_app_blog_author_id_92ddd532_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_author_id_92ddd532_like ON public.blog_app_blog USING btree (author_id varchar_pattern_ops);


--
-- Name: blog_app_blog_category_id_922977aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_category_id_922977aa ON public.blog_app_blog USING btree (category_id);


--
-- Name: blog_app_blog_id_6c14bd44_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_id_6c14bd44_like ON public.blog_app_blog USING btree (id varchar_pattern_ops);


--
-- Name: blog_app_blog_slug_85ebb591_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_slug_85ebb591_like ON public.blog_app_blog USING btree (slug varchar_pattern_ops);


--
-- Name: blog_app_blog_tags_blog_id_f5ac7518; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_tags_blog_id_f5ac7518 ON public.blog_app_blog_tags USING btree (blog_id);


--
-- Name: blog_app_blog_tags_blog_id_f5ac7518_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_tags_blog_id_f5ac7518_like ON public.blog_app_blog_tags USING btree (blog_id varchar_pattern_ops);


--
-- Name: blog_app_blog_tags_tag_id_18012483; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blog_tags_tag_id_18012483 ON public.blog_app_blog_tags USING btree (tag_id);


--
-- Name: blog_app_blogviewer_blog_id_63fef82d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blogviewer_blog_id_63fef82d ON public.blog_app_blogviewer USING btree (blog_id);


--
-- Name: blog_app_blogviewer_blog_id_63fef82d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blogviewer_blog_id_63fef82d_like ON public.blog_app_blogviewer USING btree (blog_id varchar_pattern_ops);


--
-- Name: blog_app_blogviewer_viewer_id_a61b54c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blogviewer_viewer_id_a61b54c6 ON public.blog_app_blogviewer USING btree (viewer_id);


--
-- Name: blog_app_blogviewer_viewer_id_a61b54c6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_blogviewer_viewer_id_a61b54c6_like ON public.blog_app_blogviewer USING btree (viewer_id varchar_pattern_ops);


--
-- Name: blog_app_bookmark_blog_id_cd5ec323; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_bookmark_blog_id_cd5ec323 ON public.blog_app_bookmark USING btree (blog_id);


--
-- Name: blog_app_bookmark_blog_id_cd5ec323_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_bookmark_blog_id_cd5ec323_like ON public.blog_app_bookmark USING btree (blog_id varchar_pattern_ops);


--
-- Name: blog_app_bookmark_user_id_1683c64b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_bookmark_user_id_1683c64b ON public.blog_app_bookmark USING btree (user_id);


--
-- Name: blog_app_bookmark_user_id_1683c64b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_bookmark_user_id_1683c64b_like ON public.blog_app_bookmark USING btree (user_id varchar_pattern_ops);


--
-- Name: blog_app_category_name_168ba51e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_category_name_168ba51e_like ON public.blog_app_category USING btree (name varchar_pattern_ops);


--
-- Name: blog_app_category_slug_eecf6ed4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_category_slug_eecf6ed4_like ON public.blog_app_category USING btree (slug varchar_pattern_ops);


--
-- Name: blog_app_comment_blog_id_f2b2fc5b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_comment_blog_id_f2b2fc5b ON public.blog_app_comment USING btree (blog_id);


--
-- Name: blog_app_comment_blog_id_f2b2fc5b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_comment_blog_id_f2b2fc5b_like ON public.blog_app_comment USING btree (blog_id varchar_pattern_ops);


--
-- Name: blog_app_comment_parent_id_2f5860e7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_comment_parent_id_2f5860e7 ON public.blog_app_comment USING btree (parent_id);


--
-- Name: blog_app_comment_user_id_ca767d13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_comment_user_id_ca767d13 ON public.blog_app_comment USING btree (user_id);


--
-- Name: blog_app_comment_user_id_ca767d13_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_comment_user_id_ca767d13_like ON public.blog_app_comment USING btree (user_id varchar_pattern_ops);


--
-- Name: blog_app_like_blog_id_c43a72c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_like_blog_id_c43a72c2 ON public.blog_app_like USING btree (blog_id);


--
-- Name: blog_app_like_blog_id_c43a72c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_like_blog_id_c43a72c2_like ON public.blog_app_like USING btree (blog_id varchar_pattern_ops);


--
-- Name: blog_app_like_user_id_3dc65ee1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_like_user_id_3dc65ee1 ON public.blog_app_like USING btree (user_id);


--
-- Name: blog_app_like_user_id_3dc65ee1_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_like_user_id_3dc65ee1_like ON public.blog_app_like USING btree (user_id varchar_pattern_ops);


--
-- Name: blog_app_tag_name_58316e81_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_app_tag_name_58316e81_like ON public.blog_app_tag USING btree (name varchar_pattern_ops);


--
-- Name: calendar_app_event_created_by_id_7a67b3d3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX calendar_app_event_created_by_id_7a67b3d3 ON public.calendar_app_event USING btree (created_by_id);


--
-- Name: calendar_app_event_created_by_id_7a67b3d3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX calendar_app_event_created_by_id_7a67b3d3_like ON public.calendar_app_event USING btree (created_by_id varchar_pattern_ops);


--
-- Name: calendar_app_event_customer_id_4bb22777; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX calendar_app_event_customer_id_4bb22777 ON public.calendar_app_event USING btree (customer_id);


--
-- Name: calendar_app_event_employee_id_39c7b826; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX calendar_app_event_employee_id_39c7b826 ON public.calendar_app_event USING btree (employee_id);


--
-- Name: calendar_app_event_employee_id_39c7b826_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX calendar_app_event_employee_id_39c7b826_like ON public.calendar_app_event USING btree (employee_id varchar_pattern_ops);


--
-- Name: career_app_answer_question_id_d7ff1c82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_answer_question_id_d7ff1c82 ON public.career_app_answer USING btree (question_id);


--
-- Name: career_app_answer_selected_options_answer_id_60d3bd39; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_answer_selected_options_answer_id_60d3bd39 ON public.career_app_answer_selected_options USING btree (answer_id);


--
-- Name: career_app_answer_selected_options_option_id_539616de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_answer_selected_options_option_id_539616de ON public.career_app_answer_selected_options USING btree (option_id);


--
-- Name: career_app_careerapplication_career_id_a9cfee4c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_careerapplication_career_id_a9cfee4c ON public.career_app_careerapplication USING btree (career_id);


--
-- Name: career_app_careerapplication_id_d3acf9bc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_careerapplication_id_d3acf9bc_like ON public.career_app_careerapplication USING btree (id varchar_pattern_ops);


--
-- Name: career_app_option_question_id_bae4ff2a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_option_question_id_bae4ff2a ON public.career_app_option USING btree (question_id);


--
-- Name: career_app_question_career_id_77f8f6f9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_question_career_id_77f8f6f9 ON public.career_app_question USING btree (career_id);


--
-- Name: career_app_requirement_career_id_cbf8fc9a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX career_app_requirement_career_id_cbf8fc9a ON public.career_app_requirement USING btree (career_id);


--
-- Name: cms_taxpayer_id_2a1722ea_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cms_taxpayer_id_2a1722ea_like ON public.cms_taxpayer USING btree (id varchar_pattern_ops);


--
-- Name: cms_taxpayermedia_taxpayer_id_6132f6b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cms_taxpayermedia_taxpayer_id_6132f6b6 ON public.cms_taxpayermedia USING btree (taxpayer_id);


--
-- Name: cms_taxpayermedia_taxpayer_id_6132f6b6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cms_taxpayermedia_taxpayer_id_6132f6b6_like ON public.cms_taxpayermedia USING btree (taxpayer_id varchar_pattern_ops);


--
-- Name: customers_customer_customer_id_4c877f6e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_customer_customer_id_4c877f6e_like ON public.customers_customer USING btree (customer_id varchar_pattern_ops);


--
-- Name: customers_customer_email_300e404b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_customer_email_300e404b_like ON public.customers_customer USING btree (email varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_admin_log_user_id_c564eba6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6_like ON public.django_admin_log USING btree (user_id varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: employee_employee_email_29cdd800_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_employee_email_29cdd800_like ON public.employee_employee USING btree (email varchar_pattern_ops);


--
-- Name: employee_employee_employee_id_f303a754_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_employee_employee_id_f303a754_like ON public.employee_employee USING btree (employee_id varchar_pattern_ops);


--
-- Name: employee_employee_id_6760aff6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_employee_id_6760aff6_like ON public.employee_employee USING btree (id varchar_pattern_ops);


--
-- Name: employee_socialmedia_employee_id_4f917205; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_socialmedia_employee_id_4f917205 ON public.employee_socialmedia USING btree (employee_id);


--
-- Name: employee_socialmedia_employee_id_4f917205_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_socialmedia_employee_id_4f917205_like ON public.employee_socialmedia USING btree (employee_id varchar_pattern_ops);


--
-- Name: payment_app_transaction_transaction_id_7ad7e809_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payment_app_transaction_transaction_id_7ad7e809_like ON public.payment_app_transaction USING btree (transaction_id varchar_pattern_ops);


--
-- Name: auth_app_user_groups auth_app_user_groups_group_id_b4576925_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_groups
    ADD CONSTRAINT auth_app_user_groups_group_id_b4576925_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_app_user_groups auth_app_user_groups_user_id_2b6e45f5_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_groups
    ADD CONSTRAINT auth_app_user_groups_user_id_2b6e45f5_fk_auth_app_user_id FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_app_user_user_permissions auth_app_user_user_p_permission_id_cc1b2396_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_user_permissions
    ADD CONSTRAINT auth_app_user_user_p_permission_id_cc1b2396_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_app_user_user_permissions auth_app_user_user_p_user_id_b7c37328_fk_auth_app_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_user_user_permissions
    ADD CONSTRAINT auth_app_user_user_p_user_id_b7c37328_fk_auth_app_ FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blog blog_app_blog_author_id_92ddd532_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog
    ADD CONSTRAINT blog_app_blog_author_id_92ddd532_fk_auth_app_user_id FOREIGN KEY (author_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blog blog_app_blog_category_id_922977aa_fk_blog_app_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog
    ADD CONSTRAINT blog_app_blog_category_id_922977aa_fk_blog_app_category_id FOREIGN KEY (category_id) REFERENCES public.blog_app_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blog_tags blog_app_blog_tags_blog_id_f5ac7518_fk_blog_app_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog_tags
    ADD CONSTRAINT blog_app_blog_tags_blog_id_f5ac7518_fk_blog_app_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog_app_blog(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blog_tags blog_app_blog_tags_tag_id_18012483_fk_blog_app_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blog_tags
    ADD CONSTRAINT blog_app_blog_tags_tag_id_18012483_fk_blog_app_tag_id FOREIGN KEY (tag_id) REFERENCES public.blog_app_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blogviewer blog_app_blogviewer_blog_id_63fef82d_fk_blog_app_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blogviewer
    ADD CONSTRAINT blog_app_blogviewer_blog_id_63fef82d_fk_blog_app_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog_app_blog(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_blogviewer blog_app_blogviewer_viewer_id_a61b54c6_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_blogviewer
    ADD CONSTRAINT blog_app_blogviewer_viewer_id_a61b54c6_fk_auth_app_user_id FOREIGN KEY (viewer_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_bookmark blog_app_bookmark_blog_id_cd5ec323_fk_blog_app_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_bookmark
    ADD CONSTRAINT blog_app_bookmark_blog_id_cd5ec323_fk_blog_app_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog_app_blog(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_bookmark blog_app_bookmark_user_id_1683c64b_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_bookmark
    ADD CONSTRAINT blog_app_bookmark_user_id_1683c64b_fk_auth_app_user_id FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_comment blog_app_comment_blog_id_f2b2fc5b_fk_blog_app_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_comment
    ADD CONSTRAINT blog_app_comment_blog_id_f2b2fc5b_fk_blog_app_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog_app_blog(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_comment blog_app_comment_parent_id_2f5860e7_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_comment
    ADD CONSTRAINT blog_app_comment_parent_id_2f5860e7_fk FOREIGN KEY (parent_id) REFERENCES public.blog_app_comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_comment blog_app_comment_user_id_ca767d13_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_comment
    ADD CONSTRAINT blog_app_comment_user_id_ca767d13_fk_auth_app_user_id FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_like blog_app_like_blog_id_c43a72c2_fk_blog_app_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_like
    ADD CONSTRAINT blog_app_like_blog_id_c43a72c2_fk_blog_app_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog_app_blog(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: blog_app_like blog_app_like_user_id_3dc65ee1_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_app_like
    ADD CONSTRAINT blog_app_like_user_id_3dc65ee1_fk_auth_app_user_id FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: calendar_app_event calendar_app_event_created_by_id_7a67b3d3_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_app_event
    ADD CONSTRAINT calendar_app_event_created_by_id_7a67b3d3_fk_auth_app_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: calendar_app_event calendar_app_event_customer_id_4bb22777_fk_customers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_app_event
    ADD CONSTRAINT calendar_app_event_customer_id_4bb22777_fk_customers FOREIGN KEY (customer_id) REFERENCES public.customers_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: calendar_app_event calendar_app_event_employee_id_39c7b826_fk_employee_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_app_event
    ADD CONSTRAINT calendar_app_event_employee_id_39c7b826_fk_employee_employee_id FOREIGN KEY (employee_id) REFERENCES public.employee_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_answer career_app_answer_question_id_d7ff1c82_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer
    ADD CONSTRAINT career_app_answer_question_id_d7ff1c82_fk FOREIGN KEY (question_id) REFERENCES public.career_app_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_answer_selected_options career_app_answer_selected_options_answer_id_60d3bd39_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer_selected_options
    ADD CONSTRAINT career_app_answer_selected_options_answer_id_60d3bd39_fk FOREIGN KEY (answer_id) REFERENCES public.career_app_answer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_answer_selected_options career_app_answer_selected_options_option_id_539616de_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_answer_selected_options
    ADD CONSTRAINT career_app_answer_selected_options_option_id_539616de_fk FOREIGN KEY (option_id) REFERENCES public.career_app_option(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_careerapplication career_app_careerapplication_career_id_a9cfee4c_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_careerapplication
    ADD CONSTRAINT career_app_careerapplication_career_id_a9cfee4c_fk FOREIGN KEY (career_id) REFERENCES public.career_app_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_option career_app_option_question_id_bae4ff2a_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_option
    ADD CONSTRAINT career_app_option_question_id_bae4ff2a_fk FOREIGN KEY (question_id) REFERENCES public.career_app_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_question career_app_question_career_id_77f8f6f9_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_question
    ADD CONSTRAINT career_app_question_career_id_77f8f6f9_fk FOREIGN KEY (career_id) REFERENCES public.career_app_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: career_app_requirement career_app_requirement_career_id_cbf8fc9a_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_app_requirement
    ADD CONSTRAINT career_app_requirement_career_id_cbf8fc9a_fk FOREIGN KEY (career_id) REFERENCES public.career_app_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cms_taxpayermedia cms_taxpayermedia_taxpayer_id_6132f6b6_fk_cms_taxpayer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cms_taxpayermedia
    ADD CONSTRAINT cms_taxpayermedia_taxpayer_id_6132f6b6_fk_cms_taxpayer_id FOREIGN KEY (taxpayer_id) REFERENCES public.cms_taxpayer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_app_user_id FOREIGN KEY (user_id) REFERENCES public.auth_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_socialmedia employee_socialmedia_employee_id_4f917205_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_socialmedia
    ADD CONSTRAINT employee_socialmedia_employee_id_4f917205_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

