# Generated by Django 5.2.16 on 2026-08-05 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplacePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('TRIAL', 'Trial'), ('INSTALLATION', 'Installation'), ('UPDATE', 'Update'), ('ROLLBACK', 'Rollback')], max_length=20)),
                ('product_code', models.CharField(max_length=100)),
                ('package_version', models.CharField(blank=True, max_length=40)),
                ('subscription_reference', models.CharField(max_length=120)),
                ('entitlement_reference', models.CharField(max_length=120)),
                ('approval_reference', models.CharField(blank=True, max_length=120)),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('middleware_reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='PENDING_MIDDLEWARE', max_length=32)),
                ('audit_context', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProspectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.CharField(max_length=160)),
                ('purpose', models.CharField(max_length=240)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('geography', models.JSONField(default=list)),
                ('minimum_score', models.PositiveSmallIntegerField(default=0)),
                ('required_verification', models.CharField(default='VERIFIED', max_length=24)),
                ('suppression_policy', models.JSONField(default=dict)),
                ('expiration', models.DateTimeField()),
                ('status', models.CharField(default='DRAFT', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_domain', models.CharField(db_index=True, max_length=253)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_timestamp', models.DateTimeField()),
                ('verification_state', models.CharField(default='UNVERIFIED', max_length=24)),
                ('enrichment', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(default='QUEUED', max_length=32)),
                ('policy', models.JSONField(default=dict)),
                ('request', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('middleware_reference', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerCAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('actor_reference', models.CharField(max_length=160)),
                ('resource_reference', models.CharField(max_length=200)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('supported_industries', models.JSONField(default=list)),
                ('supported_platform_versions', models.JSONField(default=list)),
                ('required_permissions', models.JSONField(default=list)),
                ('required_capabilities', models.JSONField(default=list)),
                ('required_connectors', models.JSONField(default=list)),
                ('installation_scope', models.CharField(default='STAGING', max_length=40)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('trial_available', models.BooleanField(default=False)),
                ('documentation_reference', models.URLField(blank=True)),
                ('support_reference', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('SECURITY_REVIEW', 'Security Review'), ('BUSINESS_REVIEW', 'Business Review'), ('APPROVED_FOR_STAGING', 'Approved For Staging'), ('STAGING_VISIBLE', 'Staging Visible'), ('PAUSED', 'Paused'), ('DEPRECATED', 'Deprecated'), ('RETIRED', 'Retired'), ('APPROVED_FOR_PRODUCTION_REVIEW', 'Approved For Production Review'), ('PRODUCTION_VISIBLE', 'Production Visible')], db_index=True, default='DRAFT', max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('language', models.CharField(default='en', max_length=12)),
                ('tags', models.JSONField(default=list)),
                ('pricing_reference', models.CharField(blank=True, max_length=120)),
                ('support_tier', models.CharField(blank=True, max_length=40)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server_c.marketplacecategory')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server_c.marketplacepublisher')),
            ],
        ),
        migrations.CreateModel(
            name='SalesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('email_candidate', models.EmailField(blank=True, max_length=254)),
                ('phone_candidate', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('verification_state', models.CharField(default='UNVERIFIED', max_length=24)),
                ('source', models.URLField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='server_c.salescompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplacePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.SlugField(max_length=100)),
                ('package_version', models.CharField(max_length=40)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=128)),
                ('signature_reference', models.CharField(max_length=300)),
                ('rollback_version', models.CharField(max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='server_c.marketplaceproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package_code', 'package_version'), name='unique_marketplace_package_version')],
            },
        ),
    ]
