# Generated by Django 5.2.17 on 2026-10-08 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=128)),
                ('contact_id', models.CharField(max_length=128)),
                ('widget_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('last_message', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sms_consent', models.CharField(choices=[('unknown', 'Unknown'), ('withdrawn', 'Withdrawn')], default='unknown', max_length=16)),
                ('allow_external_contact', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('location_id', 'contact_id'), name='lc_unique_contact_location')],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=128)),
                ('event_key', models.CharField(max_length=256)),
                ('body_sha256', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='received', max_length=16)),
                ('consent_evidence', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('location_id', 'event_key'), name='lc_unique_event_location')],
            },
        ),
    ]
